### ISSUE TITLE
PR review is taking way too long

### ISSUE THREAD

**Issue by addy1997** [TheAlgorithms/Go#226]

**Comment by Mystigan** [comment]
@addy1997 , your PR for radix sort was opened roughly an hour ago. 
In general, reviews and merges may be affected by:
- time zone differences.
- Multiple PRs addressing same issue/algorithm. We have to review each one and decide on which to merge.(This is the case for radix sort implementations. There are 4-5 PRs currently open for this.)
- Unavailability of reviewers due to some personal reason (school, job , etc.).

Please be patient. We will provide feedback to your contribution as soon as we can.

**Comment by addy1997** [comment]
> @addy1997 , your PR for radix sort was opened roughly an hour ago.
> In general, reviews and merges may be affected by:
> 
>     * time zone differences.
> 
>     * Multiple PRs addressing same issue/algorithm. We have to review each one and decide on which to merge.(This is the case for radix sort implementations. There are 4-5 PRs currently open for this.)
> 
>     * Unavailability of reviewers due to some personal reason (school, job , etc.).
> 
> 
> Please be patient. We will provide feedback to your contribution as soon as we can.

@Mystigan Okay !!, I will be patient
