### ISSUE TITLE
Algorithms that have no tests

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Go#272]
From our GitHub Actions...
`go test $(go list ./... | grep -v /sbom | grep -v /rsa)`
* [ ] ciphers	[no test files]
* [ ] datastructures/binary-tree	[no test files]
* [ ] datastructures/dynamic-array	[no test files]
* [ ] datastructures/linkedlist/doublylinkedlist	[no test files]
* [ ] graphs/breathfirstsearch	[no test files]
* [ ] graphs/depthfirstsearch	[no test files]
* [ ] graphs/floydwarshall	[no test files]
* [ ] other/maxsubarraysum	[no test files]
* [ ] other/nestedbrackets	[no test files]
* [ ] other/passwordgenerator	[no test files]
* [ ] other/stringcombinations	[no test files]
* [ ] strings/single-string-matching/bom	[no test files]
* [ ] strings/single-string-matching/horspool	[no test files]

**Comment by tjgurwara99** [comment]
This is an updated list of missing tests:

* [ ]       github.com/TheAlgorithms/Go/data_structures/binary_tree [no test files]
* [ ]       github.com/TheAlgorithms/Go/data_structures/set [no test files]
* [ ]       github.com/TheAlgorithms/Go/genetic_algorithm   [no test files]
* [ ]       github.com/TheAlgorithms/Go/graphs/depth_first_search   [no test files]
* [ ]       github.com/TheAlgorithms/Go/graphs/floyd_warshall       [no test files]
* [ ]       github.com/TheAlgorithms/Go/math/lcm    [no test files]
* [ ]       github.com/TheAlgorithms/Go/other/max_subarray_sum      [no test files]
* [ ]       github.com/TheAlgorithms/Go/other/nested_brackets       [no test files]
* [ ]       github.com/TheAlgorithms/Go/other/password_generator    [no test files]
* [ ]       github.com/TheAlgorithms/Go/other/string_combinations   [no test files]
* [ ]       github.com/TheAlgorithms/Go/strings/single_string_matching/bom  [no test files]
* [ ]       github.com/TheAlgorithms/Go/strings/single_string_matching/horspool     [no test files]

**Comment by tjgurwara99** [comment]
We need tests for the following algorithms:

* [ ]     github.com/TheAlgorithms/Go/strings/bom [no test files] 
* [ ]     github.com/TheAlgorithms/Go/strings/combination [no test files]
* [ ]     github.com/TheAlgorithms/Go/strings/horspool    [no test files]
* [ ]     github.com/TheAlgorithms/Go/structure/binarytree        [no test files]
* [ ]      github.com/TheAlgorithms/Go/structure/set       [no test files]

---

The following is a list of directories that do not have tests and also do have anything that can be tested:

* [ ]     github.com/TheAlgorithms/Go/structure   [no test files] – This doesn't need a test because it has nothing in it, all its sub-packages have their own test files.
* [ ]       github.com/TheAlgorithms/Go/cipher      [no test files]  – This doesn't need a test because it has nothing in it, all its sub-packages have their own test files.
* [ ]      github.com/TheAlgorithms/Go/other       [no test files] – This doesn't need a test because it has nothing in it, all its sub-packages have their own test files.
* [ ]     github.com/TheAlgorithms/Go/strings     [no test files] – This doesn't need a test because it has nothing in it, all its sub-packages have their own test files.

We can have that these have an empty test file in each directory and this would mean that it wouldn't raise a `[no test files]` error but rather `[no tests to run]` message. 
---

The following cannot have a test (in my opinion) - if anyone has an idea of use being able to test it then let me know!

* [ ]     github.com/TheAlgorithms/Go/other/password      [no test files] – This cannot have a fully covered test because of the inherent randomness in the password generator.

**Comment by siriak** [comment]
Let's remove github.com/TheAlgorithms/Go/other/password since it's not a useful well-known algorithm. I agree to add empty test files as you described.

**Comment by cclauss** [comment]
I don't think that the collection of algorithms should be a popularity contest.  I believe that some basic tests can be done on the generated passwords even if we do not know what they are beforehand.  These days every system that takes a password has tests to ensure that the password is at least a certain number of characters, contains at least one lowercase character, at least one uppercase character, at least one number, at least one punctuation character, etc.

**Comment by raklaptudirm** [comment]
The thing is, generating password have many different approaches. Even if you select 3-4 random english words for your password, mathematically, it will be really hard to brute force, even when there is no special characters or different cases.

![A little image](https://dropbox.tech/cms/content/dam/dropbox/tech-blog/en-us/2012/04/password_strength.png)
